###  开发环境 ###
###################  spring  ###################
server:
  port: 8092
spring:
############### i18n #####################
#  messages:
#    encoding: UTF-8
#    basename: i18n.xywg
##############数据库######################
  datasource:
    url: jdbc:mysql://192.168.0.52:3306/honghu_bc?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
    password: 123456





###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:**/mapper/xml/*.xml
  typeAliasesPackage: com.honghu.*.entity
  global-config:
    banner: false
    db-config:
      id-type: id_worker  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      db-column-underline: true
      refresh-mapper: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
logging:
  level:
    com.honghu: info




